fix: Update bossterm-compose to 1.0.92 and boss-plugin-api to 1.0.24
Fixes NoSuchMethodError on TabbedTerminal caused by method signature
change in bossterm-compose 1.0.92.